#!/bin/bash

# Prompter 可视化演示脚本

echo "🎬 演示新的可视化Shell监控功能"
echo "========================================="
echo ""

# 显示启动横幅预览
echo "1️⃣ 启动横幅预览:"
echo ""
echo "============================================================"
echo "🤖 PROMPTER SHELL MONITOR v1.0"
echo "   独立终端监控模式 - Claude提示词智能收集"
echo "============================================================"
echo "⏰ 启动时间: $(date '+%Y-%m-%d %H:%M:%S')"
echo "🔧 监控间隔: 5秒"
echo "------------------------------------------------------------"
echo ""

# 显示监控状态
echo "2️⃣ 监控状态总览:"
echo "------------------------------------------------------------"
echo "🖥️  活跃终端 (2 个):"
echo "   ✅ Terminal.app"
echo "   ✅ iTerm.app"
echo ""
echo "📂 监控文件 (2 个):"
echo "   ✅ /Users/$(whoami)/.zsh_history (25610 bytes)"
echo "   ✅ /Users/$(whoami)/.bash_history (75081 bytes)"
echo ""
echo "🎯 目标命令模式:"
echo "   📝 claude"
echo "   📝 claude-code"
echo "   📝 claude-cli"
echo "------------------------------------------------------------"
echo "🚀 监控服务已就绪，等待Claude命令..."
echo ""

# 显示HTTP状态码风格响应
echo "3️⃣ HTTP状态码风格响应示例:"
echo ""
echo "📥 [$(date '+%H:%M:%S.123')] 200 OK - 中文提示词已保存 | Records: 1"
echo "   └─ 📄 Content: 帮我写一个计算斐波那契数列的Python函数..."
echo ""
echo "📥 [$(date '+%H:%M:%S.456')] 200 OK - 中文提示词已保存 | Records: 2"
echo "   └─ 📄 Content: 优化这段代码的性能，让它运行得更快..."
echo ""
echo "📥 [$(date '+%H:%M:%S.789')] 200 OK - 中文提示词已保存 | Records: 3"
echo "   └─ 📄 Content: 设计一个用户登录系统的数据库结构..."
echo ""

# 显示实时监控界面
echo "4️⃣ 实时监控界面:"
echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║                    🤖 PROMPTER MONITOR                   ║"
echo "╠══════════════════════════════════════════════════════════╣"
echo "║ 活跃终端:  2 │ 成功记录:    3 │ 监控文件:  2        ║"
echo "║ 最后检查: $(date '+%H:%M:%S')                       ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

echo "✨ 核心功能特性:"
echo ""
echo "🔍 独立监控 - 无需PTY包装，对Claude Code零影响"
echo "🖥️  终端检测 - 自动检测活跃的终端应用和TTY会话"
echo "📊 状态跟踪 - 实时显示成功记录数和监控状态"
echo "🕐 时间戳 - 毫秒级精度的时间记录"
echo "📄 内容预览 - 智能截取提示词内容预览"
echo "🎯 HTTP风格 - 200 OK状态码表示成功保存"
echo ""

echo "🚀 启动方法:"
echo ""
echo "# 基础监控模式"
echo "./target/release/prompter --shell-monitor"
echo ""
echo "# 自动上传模式"
echo "./target/release/prompter --auto --shell-monitor"
echo ""
echo "# 可视化启动向导"
echo "./start_visual_monitor.sh"
echo ""

echo "========================================="
echo "🎯 新功能已实现！立即体验可视化监控界面"